"""Clone an existing subproject into a parallel top-level replica.

Strategy "B" for statistical replicas — instead of nesting ``<sys>/rep2/``
inside each subsystem, create a fully independent top-level subproject:

    Gelatin/         (rep1, original)
    Gelatin_rep2/    (replica 2, full Workflow 1 from scratch)
    Gelatin_rep3/    (replica 3, full Workflow 1 from scratch)
    Gel1MA/
    Gel1MA_rep2/
    Gel1MA_rep3/
    ...

This gives **maximum statistical independence**: different Packmol packing,
different psfgen ordering, different velocities. The standard for N≥3 MD
publications.

Trade-off vs the nested ``prep_replica.py`` approach:

  - Pro : full independence (Packmol packing differs); pipeline scripts
          (``auto_extend.py``, ``NPT_conti.py``, ``refresh_confs.py``) work
          without any code changes — just add the new dir name to
          ``workflow2.TARGET_SYSTEMS``.
  - Con : ~5 GB per rep on disk (vs ~2 GB nested); slower to bootstrap
          (a full Workflow 1 NVT + NPT run, vs reusing rep1's PSF/PDB).

What this script copies (= what's needed for Workflow 1 to run fresh):
    config.json
    main.py
    input/
    packmol/  (incl. packmol.exe + water.pdb + sodium.pdb / chloride.pdb if present)
    script/   (incl. force-field + conf templates + topology)

What this script DOES NOT copy (= runtime artefacts you want fresh):
    Output/, temp/, *.dcd, *.coor, *.vel, *.xst, *.xsc, *.log, *.BAK, *.old

Seed injection
--------------
Optionally drops ``seed <N>`` near the top of ``script/NVT.conf`` in the
clone, so the new subproject's NVT velocity init uses a deterministic
distinct stream. Skip with ``--no-seed`` to let NAMD use its time-based
default each time (also gives independence but is non-reproducible).
"""
from __future__ import annotations

import argparse
import logging
import re
import shutil
import sys
from pathlib import Path

log = logging.getLogger(__name__)
# This copy lives in `production/sim_scripts/`; system folders (Gelatin/,
# Gel1MA/, ...) and clone outputs (<sys>_rep2/, ...) live one level up under
# `production/`. Resolve ROOT_DIR there so clones land alongside the
# originals and auto_extend.py / data_analysis.py pick them up.
ROOT_DIR: Path = Path(__file__).resolve().parent.parent

#: Runtime artefacts / build outputs / legacy dirs that must NOT be copied —
#: they'd cause the clone to skip re-running Workflow 1 (defeats the purpose
#: of fresh Packmol packing). Names are matched case-insensitively.
EXCLUDE_TOPLEVEL_LOWER = {
    "output",       # Workflow 1 NAMD outputs
    "temp",         # Packmol / psfgen intermediates
    "rep2", "rep3", # Earlier nested replicas from prep_replica.py
    "__pycache__",  # Python bytecode
    ".claude",      # Editor state
    "model",        # Legacy preview/scratch folder
}
EXCLUDE_GLOBS = (
    "*.dcd", "*.coor", "*.vel", "*.xst", "*.xsc", "*.log",
    "*.BAK", "*.old",
    "*_wb.pdb", "debug_*",      # Packmol / psfgen outputs (regenerated by main.py)
    "packmol_config*.inp",      # top-level produced packmol config (regenerated)
    # NOTE: do NOT add bare "*.pdb" patterns — `Path.match` matches against the
    # final component only, so e.g. "gelatin_2026.pdb" would also exclude the
    # canonical "Gelatin/input/gelatin_2026.pdb" that Workflow 1 requires.
)

SEED_BASE_DEFAULT: int = 20260000
SEED_STRIDE: int = 100


def _ignore_runtime(src: str, names: list[str]) -> set[str]:
    """``shutil.copytree`` ignore callback — drops runtime artefacts.

    Case-insensitive folder match for the well-known runtime dirs, and
    glob-pattern match for known build-output files at any depth.
    """
    ignore: set[str] = set()
    src_path = Path(src)
    for name in names:
        full = src_path / name
        # Folder-level exclusion (case-insensitive)
        if full.is_dir() and name.lower() in EXCLUDE_TOPLEVEL_LOWER:
            ignore.add(name)
            continue
        # File-pattern exclusion
        if full.is_file():
            for pattern in EXCLUDE_GLOBS:
                if full.match(pattern):
                    ignore.add(name)
                    break
    return ignore


def _patch_seed(nvt_conf: Path, seed: int) -> None:
    """Inject ``seed <N>`` directive into the cloned NVT.conf."""
    text = nvt_conf.read_text(encoding="utf-8")
    seed_line = f"seed                {seed}"
    if re.search(r"^\s*seed\s+\d+", text, re.MULTILINE):
        text = re.sub(r"^\s*seed\s+\d+", seed_line, text, count=1, flags=re.MULTILINE)
    elif "set temperature" in text:
        text = text.replace("set temperature", f"{seed_line}\nset temperature", 1)
    else:
        text = seed_line + "\n" + text
    nvt_conf.write_text(text, encoding="utf-8")


def _seed_for(rep_label: str, base: int) -> int:
    m = re.search(r"\d+", rep_label)
    n = int(m.group(0)) if m else 0
    return base + n * SEED_STRIDE


def clone(src_name: str, dest_name: str, *, seed: int | None,
          force: bool = False) -> bool:
    src = ROOT_DIR / src_name
    dest = ROOT_DIR / dest_name
    if not src.exists():
        log.error("Source %s does not exist.", src)
        return False
    if dest.exists():
        if not force:
            log.error("Destination %s already exists. Pass --force to overwrite.", dest)
            return False
        log.warning("--force: removing existing %s", dest)
        shutil.rmtree(dest)

    log.info("Cloning %s → %s ...", src_name, dest_name)
    shutil.copytree(src, dest, ignore=_ignore_runtime)

    # Inject seed into the cloned script/NVT.conf (the user's main.py path
    # will then propagate it through prepare_configs to Output/NVT.conf).
    if seed is not None:
        nvt_conf = dest / "script" / "NVT.conf"
        if nvt_conf.exists():
            _patch_seed(nvt_conf, seed)
            log.info("Seed = %d injected into %s", seed, nvt_conf.relative_to(ROOT_DIR))
        else:
            log.warning("script/NVT.conf missing in clone — skipped seed injection.")

    # Sanity-check the clone has the bare essentials.
    needed = ["config.json", "main.py", "input", "packmol", "script"]
    missing = [n for n in needed if not (dest / n).exists()]
    if missing:
        log.warning("Clone missing essential parts: %s", missing)
        return False

    log.info("Clone complete: %s", dest)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Clone subsystem(s) into top-level statistical replicas.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  # Clone all 4 systems into _rep2 variants with seed 20260200\n"
            "  python clone_subproject.py --rep rep2\n\n"
            "  # Same but pick a specific seed base\n"
            "  python clone_subproject.py --rep rep2 --seed-base 20260515\n\n"
            "  # Clone only one source manually\n"
            "  python clone_subproject.py --src Gelatin --dest Gelatin_test\n"
        ),
    )
    parser.add_argument("--rep", help="Bulk mode: clone all 4 base systems into "
                                      "<sys>_<rep> (e.g. rep2 → Gelatin_rep2, ...).")
    parser.add_argument("--src", help="Single-clone mode: source subproject name.")
    parser.add_argument("--dest", help="Single-clone mode: destination subproject name.")
    parser.add_argument("--seed-base", type=int, default=SEED_BASE_DEFAULT,
                        help=f"Base seed for rep mode (default: {SEED_BASE_DEFAULT}).")
    parser.add_argument("--seed", type=int, help="Explicit seed for --src/--dest mode.")
    parser.add_argument("--no-seed", action="store_true",
                        help="Skip seed injection (use NAMD time-based default).")
    parser.add_argument("--systems", nargs="*",
                        help="Bulk mode: subset of base systems (default: all 4).")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite destination if it exists.")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
    log.info("Project root: %s", ROOT_DIR)

    if args.rep:
        if not args.rep.startswith("rep") or args.rep == "rep1":
            log.error("--rep must look like rep2 / rep3 (rep1 = the original).")
            return 2
        bases = args.systems or ["Gelatin", "Gel1MA", "Gel2MA", "Gel3MA"]
        seed_per_rep = None if args.no_seed else _seed_for(args.rep, args.seed_base)
        log.info("Bulk clone: rep=%s, seed=%s, systems=%s",
                 args.rep, seed_per_rep, bases)

        ok, failed = 0, 0
        for base in bases:
            dest = f"{base}_{args.rep}"
            log.info("=== %s → %s ===", base, dest)
            if clone(base, dest, seed=seed_per_rep, force=args.force):
                ok += 1
            else:
                failed += 1
        log.info("Bulk done. %d cloned, %d failed.", ok, failed)
        return 0 if failed == 0 else 1

    if args.src and args.dest:
        seed = None if args.no_seed else args.seed
        log.info("Single clone: %s → %s, seed=%s", args.src, args.dest, seed)
        return 0 if clone(args.src, args.dest, seed=seed, force=args.force) else 1

    parser.error("Either --rep, or --src + --dest must be supplied.")
    return 2


if __name__ == "__main__":
    sys.exit(main())
