"""Cross-system merged comparison figures (Chiu-style: DS on x-axis,
uniform fill, panel-letter labels, strong top title).

Reads `production/plot/pre_crosslink_summary.csv` (written by data_collect.py)
and produces paper-style merged figures. Default set (M1–M3) is the
protocol-QC view; M4 is an opt-in paper executive summary.

    Figure_M1_Conformational.{png,pdf}   Rg / Ree / Lp / RMSD vs DS
    Figure_M2_Interactions.{png,pdf}     4 H-bond categories + salt bridges
                                         + inter-residue contacts
    Figure_M3_MAstructure.{png,pdf}      MA-SASA + MA-MA NN + MA-MA g(r);
                                         cluster count/size/Rg dropped
                                         (cutoff-sensitive)
    Figure_M3b_RDF_detail.{png,pdf}      MA-MA g(r) + cumulative N(R)
                                         with 5 Å / 7 Å markers
    Figure_M4_vsDS.{png,pdf}             selected scatter view (opt-in only)

Style intentionally mirrors `Figure_C1_Conformation` and `Figure_C2_HBonds`
(generated by legacy `compare_plot.py`) so both series can sit next to each
other in the paper without restyling:

  * x-axis = DS% (0 / 33 / 67 / 100), one bar per system
  * one uniform pale fill colour per panel (Chiu Fig 2 style); future
    concentration scan will add side-by-side grouped bars in another colour
  * panel subtitle "(a) ..." left-aligned, bold
  * single strong top title "<Group> vs DS [× Concentration]"
  * non-stationary bars overlaid with diagonal hatching + side annotation

Run `data_collect.py` first if `pre_crosslink_summary.csv` doesn't exist.

Usage:
    python plot_merged.py               # default: M1 + M2 + M3
    python plot_merged.py --figs M1     # subset
    python plot_merged.py --figs M1 M4  # include opt-in M4
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from _shared import (  # noqa: E402
    DATA_ROOT,
    DATA_PREFIX,
    METRICS,
    PLOT_ROOT,
    REP_TAG,
    SUMMARY_CSV,
    SYSTEM_ORDER,
    SYSTEMS,
    apply_paper_style,
    save_fig,
)

# When set (via --rep), figures are built from a single replica's per-frame
# CSVs and saved with this filename suffix. Empty = ensemble/default behaviour
# (reads pre_crosslink_summary.csv, averages RDF across all replicas).
_OUT_SUFFIX: str = ""
_REP_FILTER: str | None = None  # e.g. "rep1" / "rep2"; None = all replicas


def _fig_path(stem: str) -> Path:
    """Output path for a figure stem, honoring the active per-rep suffix."""
    return PLOT_ROOT / f"{stem}{_OUT_SUFFIX}.png"

# Concentration registry — single 7.5 wt% point in current production. When
# the high-conc scan (10/15/20%) returns this lets us add grouped bars
# without rewriting the panel function.
CONCENTRATIONS: list[tuple[str, str]] = [
    ("7.5 wt%", "#5a9fd4"),     # placeholder — actual bar color comes from DS gradient below
]

# DS gradient — matches Chiu Fig 7 convention ("light to dark blue bars
# representing GGMA-16.7, GGMA-33.3, and GGMA-50"). Gelatin (DS=0%) gets
# a distinct warm tone to flag it as the no-MA control.
DS_COLORS: dict[int, str] = {
    0:   "#e8a948",   # warm gold — Gelatin control (no MA chemistry)
    33:  "#a8d0f0",   # light blue
    67:  "#5a9fd4",   # medium blue
    100: "#1e3f6e",   # dark blue
}

PANEL_LETTERS = "abcdefghijklmnop"


def _load_summary() -> pd.DataFrame:
    if not SUMMARY_CSV.exists():
        raise FileNotFoundError(
            f"{SUMMARY_CSV} not found — run data_collect.py first")
    return pd.read_csv(SUMMARY_CSV)


def _build_rep_summary(rep_label: str, window_ns: float = 5.0,
                       stationary_thresh: float = 5.0) -> pd.DataFrame:
    """Build a summary dataframe (same schema as pre_crosslink_summary.csv)
    from a SINGLE replica's per-frame CSVs.

    Lets the existing figure functions render single-replica figures without
    the cross-replica ensemble averaging baked into data_collect.py. Each
    metric's mean_eq/sem_eq are computed over the last ``window_ns`` of that
    replica's own trajectory; drift / stationary use the same |slope|·window/
    |mean| convention as data_collect.py.
    """
    import math
    rows: list[dict] = []
    for sys_name, spec in SYSTEMS.items():
        csv = DATA_ROOT / sys_name / f"{DATA_PREFIX}_{rep_label}.csv"
        if not csv.exists():
            continue
        df = pd.read_csv(csv)
        df["Time_ns"] = pd.to_numeric(df["Time_ns"], errors="coerce")
        df = df.dropna(subset=["Time_ns"]).sort_values("Time_ns")
        t_all = df["Time_ns"].to_numpy(dtype=float)
        t_max = float(t_all.max()) if len(t_all) else 0.0
        eq = df[df["Time_ns"] >= t_max - window_ns]
        n_eq = len(eq)
        for m in METRICS:
            col = m.csv_col
            base = {
                "system": sys_name, "ds_pct": spec.ds_pct, "has_ma": spec.has_ma,
                "metric": col, "label": m.label, "unit": m.unit, "group": m.group,
                "n_eq_frames": n_eq, "eq_t_start_ns": t_max - window_ns,
                "mean_stable": float("nan"), "sem_stable": float("nan"),
                "stable_t0_ns": float("nan"), "stable_t1_ns": float("nan"),
            }
            if (m.ma_only and not spec.has_ma) or col not in df.columns:
                base.update(mean_eq=float("nan"), sem_eq=float("nan"),
                            std_eq_across_frames=float("nan"),
                            drift_pct_per_window=float("nan"), stationary=True)
                rows.append(base)
                continue
            vals = pd.to_numeric(eq[col], errors="coerce").dropna()
            mean_eq = float(vals.mean()) if len(vals) else float("nan")
            std_across = float(vals.std(ddof=1)) if len(vals) > 1 else float("nan")
            sem_eq = (std_across / math.sqrt(len(vals))) if len(vals) > 1 else float("nan")
            # drift
            y_all = pd.to_numeric(df[col], errors="coerce").to_numpy(dtype=float)
            post = t_all >= 5.0
            if post.sum() >= 3 and not math.isnan(mean_eq) and abs(mean_eq) > 1e-12:
                slope = float(np.polyfit(t_all[post], y_all[post], 1)[0])
                drift = abs(slope) * window_ns / abs(mean_eq) * 100.0
            else:
                drift = float("nan")
            stationary = (not math.isnan(drift)) and drift < stationary_thresh
            base.update(mean_eq=mean_eq, sem_eq=sem_eq,
                        std_eq_across_frames=std_across,
                        drift_pct_per_window=drift, stationary=stationary)
            rows.append(base)
    return pd.DataFrame(rows)


def _ds_label(ds_pct: int) -> str:
    return f"{ds_pct}%"


def _discover_replicas(sys_name: str) -> list[tuple[str, Path]]:
    """Return [(rep_label, csv_path)] for every replica CSV available."""
    import re
    csv_pat = re.compile(rf"^{re.escape(DATA_PREFIX)}_(rep\d+)\.csv$")
    out: list[tuple[str, Path]] = []
    for p in sorted((DATA_ROOT / sys_name).glob(f"{DATA_PREFIX}_rep*.csv")):
        m = csv_pat.match(p.name)
        if m:
            out.append((m.group(1), p))
    return out


def _matched_window_from_reps(rep_csvs: list[Path],
                              window_ns: float = 5.0) -> tuple[float, float] | None:
    """Pick the matched last-N-ns window that all replicas cover.

    Returns (lo, hi) where hi = min(rep.t_max) across replicas, lo = hi - window_ns.
    """
    if not rep_csvs:
        return None
    tmaxes: list[float] = []
    for p in rep_csvs:
        df = pd.read_csv(p, usecols=["Time_ns"])
        tmaxes.append(float(df["Time_ns"].max()))
    hi = min(tmaxes)
    lo = max(0.0, hi - window_ns)
    return lo, hi


def _paired_bar_panel(ax, metric: str,
                      panel_letter: str | None = None,
                      subtitle: str | None = None,
                      window_ns: float = 5.0,
                      ma_only: bool = False) -> None:
    """Per-replica paired bars per DS, computed from raw per-frame CSVs.

    For each system, reads every ``GelMA_analysis_rep*.csv`` in that
    system's Data dir and takes the mean over the matched last-N-ns
    window (= last window_ns of the shortest replica). Bars are drawn
    side by side with replica-distinguishing fill/edge styles. An N=2
    ensemble mean ± SEM dot is overlaid in black.
    """
    ds_list = sorted({spec.ds_pct for spec in SYSTEMS.values()
                      if (spec.has_ma or not ma_only)})

    # Per-(ds, rep) means
    rows: list[dict] = []
    for ds in ds_list:
        sys_name = next((n for n, s in SYSTEMS.items() if s.ds_pct == ds), None)
        if sys_name is None:
            continue
        spec = SYSTEMS[sys_name]
        if ma_only and not spec.has_ma:
            continue
        reps = _discover_replicas(sys_name)
        if not reps:
            continue
        win = _matched_window_from_reps([p for _, p in reps], window_ns)
        if win is None:
            continue
        lo, hi = win
        for rep_label, csv in reps:
            df = pd.read_csv(csv)
            if metric not in df.columns:
                continue
            sub = df[(df["Time_ns"] >= lo) & (df["Time_ns"] <= hi)][metric].dropna()
            if sub.empty:
                continue
            rows.append({"ds": ds, "rep": rep_label,
                         "mean": float(sub.mean()),
                         "sem":  float(sub.std(ddof=1) / np.sqrt(len(sub))) if len(sub) > 1 else 0.0})
    if not rows:
        ax.text(0.5, 0.5, f"no data for\n{metric}",
                ha="center", va="center", transform=ax.transAxes, color="grey")
        ax.set_xticks([]); ax.set_yticks([])
        return

    df_rows = pd.DataFrame(rows)
    rep_labels = sorted(df_rows["rep"].unique())
    n_rep = len(rep_labels)
    ds_present = sorted(df_rows["ds"].unique())
    x = np.arange(len(ds_present))
    width = min(0.8 / max(n_rep, 1), 0.38)

    # Plot bars
    for ri, rep in enumerate(rep_labels):
        offsets = x + (ri - (n_rep - 1) / 2) * width
        means, sems = [], []
        for d in ds_present:
            row = df_rows[(df_rows["ds"] == d) & (df_rows["rep"] == rep)]
            means.append(float(row["mean"].iloc[0]) if len(row) else float("nan"))
            sems.append(float(row["sem"].iloc[0]) if len(row) else 0.0)
        # Lighter fill for rep1, deeper edge for rep2 to differentiate
        base_colors = [DS_COLORS.get(d, "#999") for d in ds_present]
        # rep1 = pale fill / rep2 = darker fill (via alpha or hatch)
        if rep == "rep1":
            fills = base_colors
            hatches = [None] * len(ds_present)
            alphas = [1.0] * len(ds_present)
        else:
            # rep2: same hue but with hatch
            fills = base_colors
            hatches = ["///"] * len(ds_present)
            alphas = [0.85] * len(ds_present)
        for j, (xj, m, s, fill, hatch, alpha) in enumerate(
            zip(offsets, means, sems, fills, hatches, alphas)
        ):
            ax.bar(xj, m, width, yerr=s, color=fill, edgecolor="black",
                   lw=0.7, hatch=hatch, alpha=alpha,
                   error_kw=dict(elinewidth=0.9, capsize=3, ecolor="black"),
                   label=f"{rep}" if j == 0 else None)

    # N=2 ensemble dot overlay
    ens_means: list[float] = []
    ens_sems: list[float] = []
    for d in ds_present:
        vals = df_rows[df_rows["ds"] == d]["mean"].tolist()
        if len(vals) >= 2:
            ens_means.append(float(np.mean(vals)))
            ens_sems.append(float(np.std(vals, ddof=1) / np.sqrt(len(vals))))
        else:
            ens_means.append(float("nan"))
            ens_sems.append(0.0)
    valid = ~np.isnan(ens_means)
    if any(valid):
        ax.errorbar(x[valid], np.array(ens_means)[valid],
                    yerr=np.array(ens_sems)[valid],
                    fmt="ko", markersize=5, capsize=5, elinewidth=1.2,
                    label=f"N={n_rep} mean ± SEM", zorder=10)

    # Axes
    ax.set_xticks(x)
    ax.set_xticklabels([_ds_label(d) for d in ds_present])
    ax.set_xlabel("Degree of substitution")
    win = _matched_window_from_reps(
        [p for ds in ds_present
         for nm, sp in SYSTEMS.items() if sp.ds_pct == ds
         for _, p in _discover_replicas(nm)],
        window_ns,
    )
    win_str = f"matched {win[0]:.0f}–{win[1]:.0f} ns" if win else ""

    # y label heuristic from summary
    row_meta = (_load_summary()[lambda d: d["metric"] == metric].iloc[0:1])
    if len(row_meta):
        label = row_meta["label"].iloc[0]
        unit = row_meta["unit"].iloc[0]
        ax.set_ylabel(f"{label}" + (f" ({unit})" if unit else ""))

    header = ""
    if panel_letter:
        header += f"({panel_letter}) "
    if subtitle:
        header += subtitle
    if header:
        ax.set_title(header, loc="left", fontweight="bold", fontsize=11, pad=8)
    if win_str:
        ax.text(0.99, 0.99, win_str, transform=ax.transAxes,
                ha="right", va="top", fontsize=8, color="#666",
                bbox=dict(facecolor="white", edgecolor="none", alpha=0.7,
                          boxstyle="round,pad=0.2"))

    ax.tick_params(axis="x", labelsize=10)
    ax.tick_params(axis="y", labelsize=9)
    ax.grid(axis="y", alpha=0.35, linestyle="--", linewidth=0.6)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(True)
        ax.spines[s].set_linewidth(0.6)
    ax.legend(loc="best", fontsize=8, frameon=False)


def _bar_panel(ax, df: pd.DataFrame, metric: str,
               panel_letter: str | None = None,
               subtitle: str | None = None,
               use_stable_for_nonstat: bool = True,
               show_legend: bool = False) -> None:
    """One Chiu-style bar panel.

    x = DS% (one bar per system).  Single uniform fill colour per concentration
    (`CONCENTRATIONS[0]` currently — pale yellow); error bars black; non-
    stationary bars overlaid with diagonal hatching when `mean_stable` is
    substituted for `mean_eq`.

    panel_letter / subtitle render as "(a) Intramolecular H-Bonds" left-aligned.
    """
    row_map = {r["system"]: r for _, r in df[df["metric"] == metric].iterrows()}
    systems_present = [s for s in SYSTEM_ORDER
                       if s in row_map and not pd.isna(row_map[s]["mean_eq"])]
    if not systems_present:
        ax.text(0.5, 0.5, f"no data for\n{metric}", ha="center", va="center",
                transform=ax.transAxes, color="grey", fontsize=9)
        ax.set_xticks([]); ax.set_yticks([])
        return

    ds_vals = [SYSTEMS[s].ds_pct for s in systems_present]
    x = np.arange(len(systems_present))
    means: list[float] = []
    sems: list[float] = []
    hatches: list[str | None] = []
    # Methodological choice: always plot mean_eq (last 5 ns) so every system uses
    # the SAME sampling window — comparability beats per-system "best estimate".
    # Non-stationary metrics are flagged with diagonal hatching but their bar
    # value is NOT silently swapped to mean_stable (different window = different
    # statistic, would mislead readers into apples-to-oranges comparison).
    # `mean_stable` / `sem_stable` remain in the CSV as diagnostic columns.
    _ = use_stable_for_nonstat  # kept for backward-compat call sites; ignored
    for s in systems_present:
        r = row_map[s]
        is_stat = bool(r.get("stationary", True))
        means.append(float(r["mean_eq"]))
        sems.append(float(r["sem_eq"]) if not pd.isna(r["sem_eq"]) else 0.0)
        hatches.append(None if is_stat else "///")

    # Per-bar color from DS gradient (Chiu Fig 7 style)
    bar_colors = [DS_COLORS.get(d, "#999999") for d in ds_vals]
    bars = ax.bar(
        x, means, width=0.65, yerr=sems,
        color=bar_colors, edgecolor="black", lw=0.8,
        error_kw=dict(elinewidth=1.0, capsize=4, ecolor="black"),
    )
    for bar, h in zip(bars, hatches):
        if h:
            bar.set_hatch(h)
            bar.set_edgecolor("black")

    # x-axis = DS%
    ax.set_xticks(x)
    ax.set_xticklabels([_ds_label(d) for d in ds_vals])
    ax.set_xlabel("Degree of substitution")
    ax.tick_params(axis="x", labelsize=10)
    ax.tick_params(axis="y", labelsize=9)

    # Light horizontal dashed grid only
    ax.grid(axis="y", alpha=0.35, linestyle="--", linewidth=0.6)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(True)
        ax.spines[s].set_linewidth(0.6)

    # Y label = "value (unit)"; no "_mean" cruft
    row0 = row_map[systems_present[0]]
    unit = f" ({row0['unit']})" if row0["unit"] else ""
    ax.set_ylabel(f"{row0['label']}{unit}", fontsize=10)

    # Panel header "(a) Subtitle"
    header = ""
    if panel_letter:
        header += f"({panel_letter}) "
    if subtitle:
        header += subtitle
    if header:
        ax.set_title(header, loc="left", fontweight="bold", fontsize=11, pad=8)

    # Note: panel-local "show_legend" is no longer used for the concentration
    # tag (single-conc; placed at figure level by `_multi_panel`). Per-bar
    # hatching annotation is also figure-level now.
    _ = show_legend


def _load_ma_rdf_ensemble(sys_name: str) -> tuple[np.ndarray, np.ndarray] | None:
    """Read all replica MA-RDF CSVs for ``sys_name`` and return (r, g_avg).

    Averages g(r) across whichever replicas exist (rep1 + rep2 + ...). Returns
    None if no MA RDF CSVs are found.
    """
    if _REP_FILTER is not None:
        # Single-replica mode: only that replica's RDF
        csvs = [DATA_ROOT / sys_name / f"{DATA_PREFIX}_{_REP_FILTER}_MA_ensemble_RDF.csv"]
        csvs = [p for p in csvs if p.exists()]
    else:
        csvs = sorted(
            (DATA_ROOT / sys_name).glob(f"{DATA_PREFIX}_rep*_MA_ensemble_RDF.csv")
        )
    if not csvs:
        return None
    accum, bins, n = None, None, 0
    for p in csvs:
        df = pd.read_csv(p)
        if "r_A" not in df.columns or "g_r" not in df.columns:
            continue
        if bins is None:
            bins = df["r_A"].to_numpy()
        g = df["g_r"].to_numpy()
        accum = g.copy() if accum is None else accum + g
        n += 1
    if n == 0 or bins is None:
        return None
    return bins, accum / n


def _rdf_panel(ax, panel_letter: str | None = None,
               subtitle: str | None = None,
               r_max_A: float = 15.0) -> None:
    """Line-plot panel: MA–MA radial distribution g(r), one line per MA-bearing
    system. Averages all available replicas (rep1 + rep2 + ...) for each
    system.

    Visual cues:
      * Solid line per DS, coloured from DS_COLORS gradient.
      * Vertical dashed line at 7 Å — Polymatic crosslinkability threshold.
      * Vertical dashed line at 5 Å — pre-network "tight contact" threshold.
      * Horizontal dotted line at g(r)=1 — bulk-mixing reference.
    """
    plotted = False
    for ds in (33, 67, 100):
        sys_name = next((n for n, spec in SYSTEMS.items() if spec.ds_pct == ds), None)
        if sys_name is None:
            continue
        rdf = _load_ma_rdf_ensemble(sys_name)
        if rdf is None:
            continue
        r, g = rdf
        mask = r <= r_max_A
        ax.plot(
            r[mask], g[mask],
            color=DS_COLORS.get(ds, "#999999"),
            lw=1.6, label=f"DS = {ds}%",
        )
        plotted = True

    if not plotted:
        ax.text(0.5, 0.5, "no MA RDF data", ha="center", va="center",
                transform=ax.transAxes, color="grey", fontsize=9)
        ax.set_xticks([]); ax.set_yticks([])
        return

    # Reference markers
    ax.axhline(1.0, color="#888888", lw=0.7, ls=":")
    for rcut, label in ((5.0, "5 Å (pre-network)"), (7.0, "7 Å (Polymatic)")):
        ax.axvline(rcut, color="#444444", lw=0.7, ls="--")
        ax.text(rcut, ax.get_ylim()[1] * 0.95, f" {rcut:.0f} Å",
                fontsize=7, color="#444444", va="top", ha="left")

    ax.set_xlim(0, r_max_A)
    ax.set_xlabel("MA–MA distance r (Å)")
    ax.set_ylabel("g(r)")
    ax.tick_params(axis="x", labelsize=9)
    ax.tick_params(axis="y", labelsize=9)
    ax.grid(axis="both", alpha=0.3, linestyle="--", linewidth=0.5)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(True)
        ax.spines[s].set_linewidth(0.6)
    ax.legend(loc="best", fontsize=8, frameon=False)

    header = ""
    if panel_letter:
        header += f"({panel_letter}) "
    if subtitle:
        header += subtitle
    if header:
        ax.set_title(header, loc="left", fontweight="bold", fontsize=11, pad=8)


def _add_figure_legend(fig, df: pd.DataFrame) -> None:
    """One legend at the figure bottom, decoding the DS color gradient and
    explaining the hatching convention."""
    from matplotlib.patches import Patch

    # DS gradient legend handles, in canonical order
    handles = [Patch(facecolor=DS_COLORS[d], edgecolor="black", linewidth=0.6,
                     label=f"DS = {d}%") for d in (0, 33, 67, 100)]

    # Add hatching marker only if some panel used it (cheap re-check)
    any_nonstat = bool(((~df["stationary"].astype(bool))
                        & df["mean_eq"].notna()).any())
    if any_nonstat:
        handles.append(
            Patch(facecolor="white", edgecolor="black", hatch="///", linewidth=0.6,
                  label="non-stationary (drift > 5% per 5 ns) —\n          bar value still uses last 5 ns for comparability")
        )

    # Concentration tag — single point right now
    handles.append(Patch(facecolor="none", edgecolor="none",
                         label=f"Concentration: {CONCENTRATIONS[0][0]}"))

    fig.legend(handles=handles, loc="lower center", ncol=min(len(handles), 4),
               bbox_to_anchor=(0.5, -0.015), fontsize=9, frameon=False,
               handlelength=1.6, columnspacing=1.4, handletextpad=0.6)


def _multi_panel(metrics_with_subtitles: list[tuple[str, str]], df: pd.DataFrame,
                 title: str, out: Path, ncols: int = 2,
                 panel_w: float = 5.0, panel_h: float = 4.2) -> None:
    """Build a Chiu-style multi-panel figure.

    `metrics_with_subtitles`: list of (metric_csv_col, panel_subtitle).
    """
    n = len(metrics_with_subtitles)
    nrows = (n + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols,
                             figsize=(panel_w * ncols, panel_h * nrows),
                             squeeze=False)
    axes_flat = axes.flatten()
    for i, (ax, (metric, subtitle)) in enumerate(zip(axes_flat, metrics_with_subtitles)):
        _bar_panel(ax, df, metric,
                   panel_letter=PANEL_LETTERS[i],
                   subtitle=subtitle)
    for ax in axes_flat[n:]:
        ax.set_visible(False)
    fig.suptitle(title, fontsize=14, fontweight="bold", y=1.005)
    # Leave room at the bottom for the figure-level legend
    fig.tight_layout(rect=(0, 0.04, 1, 0.985))
    _add_figure_legend(fig, df)
    save_fig(fig, out)
    plt.close(fig)
    print(f"  → {out.relative_to(out.parents[1])}")


def figure_M1_conformational(df: pd.DataFrame) -> None:
    _multi_panel(
        metrics_with_subtitles=[
            ("Rg_mean_A",                  "Radius of Gyration"),
            ("Ree_mean_A",                 "End-to-End Distance"),
            ("Persistence_Length_mean_A",  "Persistence Length"),
            ("RMSD_mean_A",                "Backbone RMSD"),
        ],
        df=df,
        title="Conformational Properties vs DS × Concentration",
        out=_fig_path("Figure_M1_Conformational"),
        ncols=2,
    )


def figure_M2_interactions(df: pd.DataFrame) -> None:
    # 2 rows × 3 cols layout — wider than tall so it fits a single slide
    # horizontally instead of the previous 3×2 "portrait" stack.
    _multi_panel(
        metrics_with_subtitles=[
            ("Hb_Intra_Strict",            "Intramolecular H-Bonds"),
            ("Hb_Inter_Strict",            "Intermolecular H-Bonds"),
            ("Hb_PW_Strict",               "Polymer–Water H-Bonds"),
            ("Hb_MA_Wat_Total",            "MA–Water H-Bonds"),
            ("Salt_Bridges",               "Salt Bridges"),
            ("Residue_Min_Contact_Total",  "Inter-Residue Contacts"),
        ],
        df=df,
        title="Inter- and Intra-molecular Interactions vs DS × Concentration",
        out=_fig_path("Figure_M2_Interactions"),
        ncols=3,
    )


def figure_M3_MAstructure(df: pd.DataFrame) -> None:
    """2-panel MA structure figure focused on crosslink-relevant geometry.

    Drops:
      * Cluster count / size / Rg — cutoff-sensitive; cluster-Rg variance
        was ~25% of mean at DS=100%. M3b RDF covers the same physics
        cutoff-free.
      * MA-Group SASA — value scales linearly with LMA atom count
        (Gel1/2/3MA SASA ratio ≈ 1:2:3 matches LMA count ratio), so total
        SASA carries no aggregation signal beyond stoichiometry. Per-LMA
        SASA stays nearly constant (~200 Å²) because pre-crosslink MA
        groups have not formed hydrophobic clusters yet (max cluster size
        ≈ 2 atoms, RDF N(7Å) < 0.25). Hydrophobic burial of MA is a
        *post-crosslink* phenomenon and will be reported in the
        crosslinked-network figure series.

    Keeps:
      (a) MA–MA Nearest Neighbour — direct chain-chain proximity probe
      (b) MA–MA Radial Distribution — cutoff-free aggregation fingerprint
          with 5 Å (pre-network) and 7 Å (Polymatic) reference lines
    """
    out = _fig_path("Figure_M3_MAstructure")
    # 2-panel single row.
    fig, axes = plt.subplots(1, 2, figsize=(11.0, 5.2), squeeze=False)
    axes_flat = axes.flatten()

    # (a) MA–MA Nearest Neighbour distance — bar panel
    _bar_panel(axes_flat[0], df, "MA_Inter_MinDist_NN_A",
               panel_letter="a", subtitle="MA–MA Nearest Neighbour")
    # (b) MA–MA g(r) — line panel, cutoff-free aggregation fingerprint
    _rdf_panel(axes_flat[1], panel_letter="b",
               subtitle="MA–MA Radial Distribution")

    fig.suptitle("MA-Group Geometry & Clustering vs DS × Concentration",
                 fontsize=14, fontweight="bold", y=1.005)
    fig.tight_layout(rect=(0, 0.12, 1, 0.985))
    _add_figure_legend(fig, df)
    save_fig(fig, out)
    plt.close(fig)
    print(f"  → {out.relative_to(out.parents[1])}")


def _read_box_edge_A(sys_name: str) -> float | None:
    """Return the equilibrated cubic box edge (Å) from the latest .xsc file.

    Falls back to ``calculated_box_L_Angstrom`` in config.json if the .xsc
    is missing (e.g. mid-pipeline). Returns None if neither source works.
    """
    sys_root = DATA_ROOT.parent / sys_name
    xsc_files = sorted(sys_root.glob("Output/system_npt_part*.xsc"))
    if xsc_files:
        try:
            with xsc_files[-1].open() as f:
                last = [ln for ln in f if not ln.startswith("#")][-1]
            return float(last.split()[1])  # a_x = cubic edge
        except Exception:
            pass
    # Fallback: config.json nominal value
    cfg = sys_root / "config.json"
    if cfg.exists():
        import json
        with cfg.open() as f:
            return float(json.load(f).get("calculated_box_L_Angstrom", float("nan")))
    return None


def figure_M3b_RDF_detail(df: pd.DataFrame) -> None:
    """Per-DS MA–MA radial distribution panels, Chiu-style.

    One panel per MA-bearing system (DS = 33 / 67 / 100%), single solid
    line per panel, clean axes (no gridlines, no overlay), x-range 0–10 Å.
    Mirrors Chiu 2026 Fig 3-12 layout (rows × cols = concentrations × DS;
    here we have only one concentration so a single row of three panels).

    Cumulative coordination number N(7 Å) per reference C8 is reported
    as small inset text in each panel to keep the Polymatic-threshold
    reading visible without a separate cumulative panel.
    """
    out = _fig_path("Figure_M3b_RDF_detail")

    R_MAX = 10.0
    POLYMATIC_R = 7.0
    N_CHAINS = 12
    # n MA reactive C8 atoms PER CHAIN for each DS: 1 LMA / chain × {1,2,3}
    n_ma_per_chain_by_ds = {33: 1, 67: 2, 100: 3}

    ma_systems = sorted(
        ((spec.ds_pct, name) for name, spec in SYSTEMS.items() if spec.has_ma),
        key=lambda x: x[0],
    )
    n_panels = len(ma_systems)
    if n_panels == 0:
        return

    fig, axes = plt.subplots(
        1, n_panels, figsize=(4.0 * n_panels, 4.0), squeeze=False, sharey=False,
    )
    axes_flat = axes.flatten()

    for ax, (ds, sys_name) in zip(axes_flat, ma_systems):
        rdf = _load_ma_rdf_ensemble(sys_name)
        if rdf is None:
            ax.text(0.5, 0.5, "no data", ha="center", va="center",
                    transform=ax.transAxes, color="grey")
            ax.set_xticks([]); ax.set_yticks([])
            continue
        r, g = rdf
        mask = r <= R_MAX
        colour = DS_COLORS.get(ds, "#5a9fd4")

        # Chiu-style: single solid blue line, no gridlines, no cutoff markers
        ax.plot(r[mask], g[mask], color=colour, lw=1.6)

        # Compute N(7 Å). Density factor uses **partner pool** density
        # (other-chain MA atoms only), not total MA atoms. For 12 chains with
        # m MA per chain, each reference C8 has (12−1)·m candidate partners
        # in V_box. Using the total-MA density would over-count by ~9%.
        L = _read_box_edge_A(sys_name)
        n_ma_per = n_ma_per_chain_by_ds.get(ds)
        n7_text = None
        if L and n_ma_per:
            n_partner = (N_CHAINS - 1) * n_ma_per
            rho = n_partner / (L ** 3)
            integrand = 4.0 * np.pi * r ** 2 * g
            Nr = rho * np.array([
                np.trapezoid(integrand[: i + 1], r[: i + 1]) for i in range(len(r))
            ])
            idx7 = int(np.searchsorted(r, POLYMATIC_R))
            n7_text = f"$N(7\\,\\mathrm{{\\AA}})$ = {float(Nr[idx7]):.2f}"

        # Subtle 7 Å reference: dotted, no label
        ax.axvline(POLYMATIC_R, color="#bbb", lw=0.6, ls=":", zorder=0)

        ax.set_xlim(0, R_MAX)
        ax.set_xlabel("distance (Å)")
        ax.set_ylabel("RDF")
        ax.set_title(f"{sys_name} (DS = {ds}%)",
                     loc="center", fontsize=11, fontweight="bold", pad=8)

        # Fully enclosed frame (all 4 spines), matches NVT_Convergence look.
        # Overrides apply_paper_style's global top/right=off for these QC-style
        # panels where a closed box reads more like an instrument trace.
        for s in ("top", "right", "bottom", "left"):
            ax.spines[s].set_visible(True)
            ax.spines[s].set_linewidth(0.8)
        ax.tick_params(direction="out", length=4, width=0.6)

        # Small N(7 Å) inset in upper-right corner of each panel
        if n7_text:
            ax.text(0.97, 0.97, n7_text, transform=ax.transAxes,
                    ha="right", va="top", fontsize=9, color="#333",
                    bbox=dict(facecolor="white", edgecolor="none",
                              alpha=0.85, boxstyle="round,pad=0.3"))

    fig.suptitle("MA–MA radial distribution (vinyl C8–C8)",
                 fontsize=13, fontweight="bold", y=1.00)
    fig.tight_layout(rect=(0, 0.06, 1, 0.97))

    save_fig(fig, out)
    plt.close(fig)
    print(f"  → {out.relative_to(out.parents[1])}")


# DS-axis plot (alternative to bar): shows trends as Y vs DS%
def figure_M4_vs_DS(df: pd.DataFrame) -> None:
    """Optional 4-panel: Rg / Ree / Hb_Inter / SASA_Global vs DS%."""
    metrics = [
        ("Rg_mean_A",      "Radius of gyration $R_g$ (Å)"),
        ("Ree_mean_A",     "End-to-end $R_{ee}$ (Å)"),
        ("Hb_Inter_Strict", "Inter-chain H-bonds"),
        ("SASA_Global_A2", "Total SASA (Å²)"),
    ]
    fig, axes = plt.subplots(2, 2, figsize=(9, 6.5))
    axes_flat = axes.flatten()
    for ax, (mcol, label) in zip(axes_flat, metrics):
        sub = df[df["metric"] == mcol].copy()
        if sub.empty:
            continue
        sub["ds_pct"] = pd.to_numeric(sub["ds_pct"], errors="coerce")
        sub = sub.sort_values("ds_pct")
        for _, r in sub.iterrows():
            ax.errorbar(r["ds_pct"], r["mean_eq"],
                        yerr=r["sem_eq"] if not pd.isna(r["sem_eq"]) else 0,
                        fmt="o", color=SYSTEMS[r["system"]].color,
                        markersize=9, capsize=4, elinewidth=1.2,
                        label=SYSTEMS[r["system"]].label.replace("\n", " "))
        # Connect points with thin grey line to suggest trend
        ax.plot(sub["ds_pct"], sub["mean_eq"], color="grey", lw=1.0, alpha=0.4, zorder=0)
        ax.set_xlabel("Degree of substitution (%)")
        ax.set_ylabel(label)
        ax.grid(alpha=0.3)
        ax.set_xticks([0, 33, 67, 100])
        if ax is axes_flat[0]:
            ax.legend(loc="best", fontsize=8)
    fig.suptitle("M4 · Selected metrics vs DS%", fontsize=13, fontweight="bold", y=1.00)
    fig.tight_layout()
    out = _fig_path("Figure_M4_vsDS")
    save_fig(fig, out)
    plt.close(fig)
    print(f"  → {out.relative_to(out.parents[1])}")


def _paired_multi_panel(metrics_with_subtitles: list[tuple[str, str]],
                        title: str, out: Path, ncols: int = 3,
                        panel_w: float = 5.0, panel_h: float = 4.2) -> None:
    """Multi-panel figure where each panel is a per-replica paired-bar plot."""
    n = len(metrics_with_subtitles)
    nrows = (n + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols,
                             figsize=(panel_w * ncols, panel_h * nrows),
                             squeeze=False)
    axes_flat = axes.flatten()
    for i, (ax, (metric, subtitle)) in enumerate(zip(axes_flat, metrics_with_subtitles)):
        _paired_bar_panel(ax, metric,
                          panel_letter=PANEL_LETTERS[i],
                          subtitle=subtitle,
                          ma_only=(metric in {"SASA_MA_A2", "Hb_MA_Wat_Total",
                                              "MA_Inter_MinDist_NN_A"}))
    for ax in axes_flat[n:]:
        ax.set_visible(False)
    fig.suptitle(title, fontsize=14, fontweight="bold", y=1.005)
    fig.tight_layout(rect=(0, 0.04, 1, 0.985))
    save_fig(fig, out)
    plt.close(fig)
    print(f"  → {out.relative_to(out.parents[1])}")


def figure_M1_paired(df: pd.DataFrame) -> None:
    """Per-replica paired-bar version of M1 (Rg / Ree / Lp / RMSD)."""
    _paired_multi_panel(
        metrics_with_subtitles=[
            ("Rg_mean_A",                  "Radius of Gyration"),
            ("Ree_mean_A",                 "End-to-End Distance"),
            ("Persistence_Length_mean_A",  "Persistence Length"),
            ("RMSD_mean_A",                "Backbone RMSD"),
        ],
        title="Conformational Properties — rep1 vs rep2 (matched window)",
        out=PLOT_ROOT / "Figure_M1_paired.png",
        ncols=2,
    )


def figure_M2_paired(df: pd.DataFrame) -> None:
    """Per-replica paired-bar version of M2 (6 interaction metrics)."""
    _paired_multi_panel(
        metrics_with_subtitles=[
            ("Hb_Intra_Strict",            "Intramolecular H-Bonds"),
            ("Hb_Inter_Strict",            "Intermolecular H-Bonds"),
            ("Hb_PW_Strict",               "Polymer–Water H-Bonds"),
            ("Hb_MA_Wat_Total",            "MA–Water H-Bonds"),
            ("Salt_Bridges",               "Salt Bridges"),
            ("Residue_Min_Contact_Total",  "Inter-Residue Contacts"),
        ],
        title="Inter- and Intra-molecular Interactions — rep1 vs rep2 (matched window)",
        out=PLOT_ROOT / "Figure_M2_paired.png",
        ncols=3,
    )


def figure_M3_paired(df: pd.DataFrame) -> None:
    """Per-replica paired-bar version of M3 (MA-MA NN; RDF is single-line)."""
    _paired_multi_panel(
        metrics_with_subtitles=[
            ("MA_Inter_MinDist_NN_A",      "MA–MA Nearest Neighbour"),
        ],
        title="MA-Group Geometry — rep1 vs rep2 (matched window)",
        out=PLOT_ROOT / "Figure_M3_paired.png",
        ncols=1,
        panel_w=6.0,
    )


FIGURES = {
    "M1":  figure_M1_conformational,
    "M2":  figure_M2_interactions,
    "M3":  figure_M3_MAstructure,
    "M3B": figure_M3b_RDF_detail,   # dict key uppercased to match CLI .upper();
                                    # output filename keeps lowercase "M3b"
    "M4":  figure_M4_vs_DS,
    # Per-replica paired-bar variants (opt-in)
    "M1P": figure_M1_paired,
    "M2P": figure_M2_paired,
    "M3P": figure_M3_paired,
}

# Default figure set — M4 is a paper-narrative executive summary, generated
# only on explicit request (`python plot_merged.py --figs M4`) so the default
# protocol-QC run stays focused on M1/M2/M3/M3b.
DEFAULT_FIGS = ("M1", "M2", "M3", "M3B")


def main() -> int:
    global _OUT_SUFFIX, _REP_FILTER
    ap = argparse.ArgumentParser()
    ap.add_argument("--figs", nargs="+", default=list(DEFAULT_FIGS),
                    help=f"Subset of figures to generate. Default: {' '.join(DEFAULT_FIGS)}. "
                         f"Use 'M4' explicitly for the selected-metrics scatter view; "
                         f"M1P/M2P/M3P for per-replica paired bars.")
    ap.add_argument("--rep", default=None,
                    help="Render single-replica figures from one replica's per-frame "
                         "CSVs (e.g. --rep rep1 or --rep rep2). Figures saved with a "
                         "'_<rep>' filename suffix; RDF panels use that replica only. "
                         "Default: ensemble (reads pre_crosslink_summary.csv).")
    args = ap.parse_args()

    apply_paper_style()

    if args.rep:
        _REP_FILTER = args.rep
        _OUT_SUFFIX = f"_{args.rep}"
        df = _build_rep_summary(args.rep)
        if df.empty:
            print(f"  [error] no per-frame CSVs found for {args.rep}")
            return 1
        print(f"built single-replica summary for {args.rep}: {len(df)} rows "
              f"(figures get '{_OUT_SUFFIX}' suffix)")
    else:
        df = _load_summary()
        print(f"loaded {len(df)} rows from {SUMMARY_CSV.name}")

    for tag in args.figs:
        fn = FIGURES.get(tag.upper())
        if fn is None:
            print(f"  [skip] unknown figure tag: {tag}")
            continue
        fn(df)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
